# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models

from .. import monkeypatch


def fix_container_time_limit(apps, schema_editor):

    Project = apps.get_model('projects.Project')
    Project.objects.filter(container_time_limit='').update(container_time_limit=0)


class Migration(migrations.Migration):
    dependencies = [
        ('docsitalia', '0013_auto_20181029_1007'),
    ]
    run_before = [
        ('projects', '0030_change-max-length-project-slug')
    ]

    operations = [
        # required by migration in projects.0035_container_time_limit_as_integer.
        migrations.RunPython(fix_container_time_limit, migrations.RunPython.noop),
    ]
