language: python
python:
  - 3.6
dist: xenial
matrix:
  include:
    - python: 3.6
      env: TOXENV=itresolver
    - python: 3.6
      env: TOXENV=py36,codecov ES_VERSION=6.3.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=docs-lint
    - python: 3.6
      env: TOXENV=lint
      script: tox
    - python: 3.6
      env: TOXENV=eslint
    - python: 3.6
      env: TOXENV=migrations

  allow_failures:
    - python: 3.6
      # This is fixed upstream - it will be fixed at next upgrade
      env: TOXENV=eslint

cache:
  directories:
    - ~/.cache/pip
    - ~/.nvm/nvm.sh
    - ~/.npm
install:
  - ./scripts/travis/install_elasticsearch.sh
  - pip install tox-travis
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install --lts
  - nvm use --lts
  - npm install -g bower
  - npm install
  - bower install
script:
  - ./scripts/travis/run_tests.sh
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always

branches:
  only:
  - master
  - rel # Community release branch
  - relcorp # Corporate release branch
  - /^dev.*$/ # docsitalia dev branch
  - /^staging.*$/ # docsitalia staging branch
  - /^production.*$/ # docsitalia production branch
  - /^italia-.*$/ # general docs italia branches

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
