# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20190703_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='default_version',
            field=models.CharField(default='bozza', help_text='The version of your project that / redirects to', max_length=255, verbose_name='Default version'),
        ),
    ]
